### ISSUE TITLE
Issue with selection

### ISSUE THREAD

**Issue by blasten** [PolymerElements/iron-list#163]
repro: http://jsfiddle.net/u794Ltzw/4/

1. [x] ~~If the items are of type number, this is wrong: https://github.com/PolymerElements/iron-list/blob/master/iron-list.html#L1231-L1234~~ Fixed in v1.2.0

2. [x] Setting the `selected` property within an item scope doesn't set the selection for that item. e.g.
```html
<template>
     ...
       <paper-checkbox checked="{{selected}}"></paper-checkbox> 
     ...       
</template>  
```

**Comment by githubGabriela** [comment]
In your fiddle the paper-checkbox doesn't work at all.
I've implemented paper-checkboxes inside iron-list and they work fine.

**Comment by blasten** [comment]
sweet.

**Comment by tgsergeant** [comment]
As far as I can tell, using checkboxes to change selection still does not work correctly.

I've modified your fiddle to illustrate this a bit more clearly:  https://jsfiddle.net/8tfnunfo/3/

When you check one of the checkboxes, the `selected` value changes *inside* the template, however, it does not propagate upwards into the `list.selectedItems`. Clicking the print button shows this, as does the deselect button, which doesn't uncheck the checkboxes.
