### ISSUE TITLE
Dynamic updates to list items not rendering properly

### ISSUE THREAD

**Issue by sfeast** [PolymerElements/iron-list#21]
I think this may be the same as #12 but that one seems to be getting convoluted so thought I'd open up these easy to reproduce steps. You can update demo1.html with the following to see the problem:

Change:
```
<iron-ajax url="data/contacts.json" last-response="{{data}}" auto></iron-ajax>
```
to
```
<iron-ajax url="data/contacts.json" on-response="dataReceived" auto></iron-ajax>
```

and add the following function:
```
        dataReceived: function(e) {
          this.data = [];
          var data = e.detail.response;
          //adds 10 items to the list every 3 seconds
          while (data.length > 0) {
            var items = data.splice(0, 10);
            this.async(function(items) {
              items.forEach(function(item){
                this.push('data', item);
              }.bind(this));
            }.bind(this, items), (50-(data.length/10)) * 3000);
          }
        }
```
to the x-app element implementation.

The idea is that instead of adding all the items directly it adds 10 at a time every 3 seconds. To see the issue:
1) Whenever new items are added scroll to the bottom of the list & wait for more items to be added.
2) You'll see a slight jump when new items are added - then scroll down a bit more to reveal them.

Result:
For the first 20 items things are ok. After that though you end up with a lot of jank. Usually items don't appear right away but then they'll flash in after waiting a bit or moving the list around.

**Comment by indolering** [comment]
Have you tried adding an observer to the child element that reinitializes the element when those properties are updated?

**Comment by indolering** [comment]
Have you tried adding an observer to the child element that reinitializes the element when those properties are updated?

**Comment by blasten** [comment]
This issue is confirmed.

**Comment by m4b** [comment]
@blasten: nice work! I have question about fix and issue.

Does:

1. this fix resolve #12
2. is this issue related to #12?

Here is an even simpler example, which fails to behave correctly in Chrome and firefox. In Firefox it only shows the first 20 items; in Chrome all the items are bunched into the first line.

I've run `bower install PolymerElements/iron-list#fix-random-access` and the fix doesn't seem to address it, so my guess is not (1 and 2).

````html
<dom-module id="list-problem">
  <style>
  :host {
    height: 100%;
  }
  </style>
  <template>
        <paper-header-panel mode="standard">
          <paper-toolbar>
            <div>list</div>
          </paper-toolbar>
            <iron-list items="[[_items]]">
              <template>
                <paper-item>[[item]]</paper-item>
              </template>
            </iron-list>
        </paper-header-panel>
  </template>
  <script>
  Polymer({
    is: 'list-problem',
    properties: {
      _items: {
        type: Array,
        notify: true,
        value: function() {
          var i = 500;
          var res = [];
          while (i--){
            res.push(i);
          }
          return res;
        }
      }
    }
  });
</script>
</dom-module>
````

**Comment by blasten** [comment]
@m4b probably!  Would you mind trying it?

**Comment by m4b** [comment]
@blasten: such sweetness !

So I've tested basically `<iron-list>` inside a `class="fit"` element, _and_ dynamic change of elements (but only by assignment) on:

* Linux Firefox
* Linux Chromium
* Android L Firefox
* Android L Chrome
* iOS 8.4 Safari

Everything works except safari, but, I don't know if it's something else is throwing it off; I was testing with a fairly complicated app, so could be anything.

Good work!

I will test tomorrow on OSX Firefox, Chrome and Safari, but I suspect it's resolved.

I should note however that when moving from smaller -> larger dataset, _sometimes_ the list is momentarily blank, until the user scrolls (or touch moves on android), and then the elements appear correctly.  That could be an unrelated issue.

I'll test some more with simpler examples like above, but I think you may have more or less resolved this issue and #12.  Again great job!

**Comment by m4b** [comment]
I tested the simple example above, and it works on FF fine.

However, on Linux Chromium I have to add:

````html
attached: function(){
      this.async(function(){
        this.$.list._refreshAll();
      }, 10);
}
````

or something thereabouts w.r.t. amount of delay.  Otherwise the elements still appear all smushed together.  So I think there's some kind of weird timing issue on Chromium on Linux (I'll test tomorrow on OSX Chrome).

But I'd say most of the major issues are gone with fit layout classes, and dynamically updating the item array.

**Comment by blasten** [comment]
@m4b I confirmed that issue in https://github.com/PolymerElements/iron-list/issues/32.

**Comment by m4b** [comment]
@blasten: it looks like #30 doesn't merge dbe70eb so pulling that branch doesn't work very well because of the problems that the latter commit fixes; but, from what I'm seeing the changes in #30 don't seem to affect the issue I'm describing, which actually doesn't seem related to a smaller -> larger dataset.  It seems to be when:

1. user scrolls a small amount, say past 20 items
2. user resets the item list
3. the list is momentarily blank until scrolling for a bit

So from what I'm seeing, #30 doesn't seem to fix this, at least in the complicated app I'm testing on, with nested headers, etc.

**Comment by blasten** [comment]
@m4b I noticed an issue because iron-list doesn't change the `scrollTop` after you reset the item list. That will result in a blank page until you scroll back to the top. Is that the same issue?  In that case, #30 sets the scroll position to `0` because the assumption is that if someone resets the item list, that list is probably different than the previous one, so there's no point on trying to keep the scroll position.

**Comment by m4b** [comment]
@blasten: 

>  I noticed an issue because iron-list doesn't change the scrollTop after you reset the item list. That will result in a blank page until you scroll back to the top. Is that the same issue?

sounds like it very well could be, actually.  Let me test again, but after doing `bower install PolymerElements/iron-list#fix-reset`, and doing the steps I wrote above, I still had a blank screen until  I scrolled to the top.

I might actually just clone iron list and merge both your fix branches and see if that clears up the issue.

**Comment by m4b** [comment]
@blasten: briefly testing this, I'm still seeing a momentary blank list after switching the items, and the scroll top isn't reset to zero, seemingly, as it is still somewhere around where it last was.

but because this is sort of getting off this issues course, I think i'll open a separate issue, and provide a fresh example, etc.

Otherwise, nice work, and maybe it's just me, but it also seems to render faster!

**Comment by blasten** [comment]
@m4b yes, please feel free. This issue in particular has been fixed in the last release.

**Comment by craftgear** [comment]
Excuse me, but I think this bug is still in there under a specific circumstance.

* iron-list is placed under paper-scroll-header-panel
* on iOS8 Safari/Chrome

After adding items when I try to scroll, the list suddenly disappears.
But I still can click items.

Here's a code to regenerate the bug.
Unfortunately it didn't work on JsBin.

```
<!doctype html>
<html>
  <head>
    <meta name="viewport" content=" width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <title>iron-list iOS items disappearance</title>
    <script src="./bower_components/webcomponentsjs/webcomponents-lite.js"></script>
    <link rel="import" href="./bower_components/iron-list/iron-list.html">
    <link rel="import" href="./bower_components/iron-pages/iron-pages.html">
    <link rel="import" href="./bower_components/paper-scroll-header-panel/paper-scroll-header-panel.html">
    <link rel="import" href="./bower_components/paper-toolbar/paper-toolbar.html">
    <dom-module id="x-app">
      <style>
        button {
          font-size: x-large;
        }
        :host {
          height: 100%;
          width: 100%;
        }
        .listItem{
          width: 99%;
          padding: 10px;
          margin-top: 5px;
          text-align: center;
          background: silver;
        }
        paper-scroll-header-panel {
          height: 100%;
        }
      </style>
      <template>
        <paper-scroll-header-panel>
        <paper-toolbar tall>
            <h1>iOS bug</h1>
        </paper-toolbar>
        <div>
          <iron-list items="[[items]]" as="item">
            <template>
              <div class="listItem" onClick="alert('clicked')">[[item.name]]</div>
            </template>
          </iron-list>
          <button on-click="addItems">add items</button>
        </div>
        </paper-scroll-header-panel>
      </template>
    </dom-module>
      <script>
        HTMLImports.whenReady(function(){
          Polymer({
              is: "x-app",
              properties: {
              items: {
                type: Array,
                value: []
              }
              },
              addItems: function(){
                for(var i=0; i < 20; i++){
                  this.push('items', {"name": "moga"});
                }
              }
            })
          }
        )
      </script>
  </head>
  <body unresolved class="fullbleed layout vertical">
    <x-app></x-app>
  </body>
</html>
```
I have no idea how to fix this bug. Any suggestions would be appreciated.

**Comment by blasten** [comment]
@sfeast can you try to see if this is still an issue?

**Comment by sfeast** [comment]
@blasten sorry for the delay, just recreated the same test here with iron-list master & related dependencies, not seeing the issue.

**Comment by blasten** [comment]
good to know
