### ISSUE TITLE
Min-height limits items.

### ISSUE THREAD

**Issue by indolering** [PolymerElements/iron-list#24]
~~The current system does not honor max-height settings, core-list did.~~  I originally thought that this was a max-height problem, but the real culprit was a min-height height setting, this would restrict the list to only displaying 20 items.

**Comment by indolering** [comment]
I originally thought that this was a max-height problem, but the real culprit was a min-height height setting, this would restrict the list to only displaying 20 items.

**Comment by indolering** [comment]
Which is to say, only 20 items out of a hundred would be rendered and I could not scroll.

**Comment by blasten** [comment]
I believe the issue here is that the list only renders a fixed number of items. We have identified this issue as a p1 priority in https://github.com/PolymerElements/iron-list/issues/10

**Comment by indolering** [comment]
@blasten If you have both min-height and max-height turned on, Polymer still only renders 20 items. If the problem is that Polymer is setting the item count based on min-height, then it doesn't matter if it cannot dynamically add more items.  But maybe I'm misunderstanding the root cause of this issue....

**Comment by blasten** [comment]
The root of the problem is that iron-list only renders 20 elements regardless of the height of your items. I'm working on the first p1 in #10

**Comment by blasten** [comment]
Btw, this issue is being addressed in #28

**Comment by indolering** [comment]
I just updated to 1.0.1 and min-height/max-height are still not respected....

**Comment by blasten** [comment]
@indolering  can you show me the css?

**Comment by indolering** [comment]
If you're not seeing this problem, then it might be an issue with my specific setup. I will close for now and reopen if I ever get around to replicating the problem with a fresh seed-element.
